### ISSUE TITLE
Fido2 Webauthn support

### ISSUE THREAD

**Issue by ladromelaboratoire** [Probesys/agentj#1]
Anti-spam systems are a major element in protecting company infrastructures from all kinds of threats.
However, the weak point of all systems is the human element and its authentication.

Is there any plan to add Fido2 WebAuthn support allowing passwords to be replaced by "password-free" authentication?

**Comment by sebastienpascalpoher** [comment]
Hello. Means of authentication other than IMAP are not planned right now. However AgentJ is under heavy development, functionalities and improvements are regularly added so this may happen someday.
