### ISSUE TITLE
Where to configure variables ??

### ISSUE THREAD

**Issue by psiraud1** [Probesys/agentj#12]
Hello,
1° ) " All you have to do is to clone the repository
# git clone https://github.com/Probesys/agentj.git
then, cd to the cloned repository to configure a few variables:
" # cd agentj-docker" should be replaced by "cd agentj"
2°) where can we change variables, seems that a "something.env" is missing.

Anyway, thanks, you have done a great job.

**Comment by ctresvaux** [comment]
Hello,
Thank you for your feedback.
We will update the readme file.
what you have to do is too rename the .env.example in .env and then initialize the differents variables.
Regards

**Comment by sjpp** [comment]
Hi, thank you for the feedback.
The README file has been updated and new specifies that  `.env.example` is just a template file that must be copied under `.env`.
