### ISSUE TITLE
Relayhost definition on .env configuration file

### ISSUE THREAD

**Issue by barthoi** [Probesys/agentj#14]
Hello,

Would it be possible to define a relayhost from the .env configuration file ?
I installed agentj on a server with a bad reputation IP, and I had to change the relayhost to something more compatible with the gafam.
So I change the configuration on the postfix docker manually. It will probably be erase at the next update.

My changes on the probesys38/agentj_relay : 
```
cat /etc/postfix/sasl_passwd
server.example.com:465 user@example.com:Mot.De,Passe

cat /etc/postfix/main.cf
[...]
relayhost = server.example.com:465
smtp_sasl_auth_enable   = yes
smtp_sasl_password_maps = texthash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_tls_wrappermode = yes
smtp_tls_security_level = encrypt
```

Thanks !

**Comment by ctresvaux** [comment]
Hello
This feature is planned in our roadmap.
It will be available in future release.
Thank you
