### ISSUE TITLE
M365 connector with mail different from userPrincipalName 

### ISSUE THREAD

**Issue by felag** [Probesys/agentj#65]
When M365 is used, it happens that mail and userPrincipalName attributes are different.

It would be nice that, after a connector to M365 is added to a domain in AgentJ, clicking Import button makes following steps:

1. Import M365 mail as AgentJ account
2. Link M365 userPrincipalName to AgentJ account to allow Microsoft auth at login
3. Import M365 proxyAdresses as AgentJ aliases, only for M365 proxyAdresses of same domain as connector
4. Import M365 groups as AgentJ groups, only for M365 groups of same domain as connector. Then import M365 group members as AgentJ group members

**Comment by ctresvaux** [comment]
This feature is now available in version 1.6.4
